### ISSUE TITLE
API to get IVR data

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-embeddable#363]
For inbound call to IVR, can we get IVR data, and support to log

**Comment by tohagan** [comment]
A security thought that you might want to consider (does not affect me).

Some IVR systems may capture private data beyond the Caller ID like a social security number or a credit card number.  In that instance, you may not want to push that data into the client. Rather, providing a key like the caller's Session Id may be sufficient to obtain the related data but not disclose it on the client in case some existing RC customers have security sensitive data captured during their IVR . In that case, you just need to document how to retrieve the IVR data related to the session via a secured API that is accessible from a server but not from the client.

**Comment by tohagan** [comment]
More design thoughts ... 

If you get IVR reponse details from a call session (e.g. the menu option numbers a customer select) and then try to decode what it all means, your code is very "coupled" to the structure of the IVR menu. Someone else is very likely to modify the IVR menu at a later date and unknowingly break your code.  

What I think you want instead is way to set a call session variable *as part of an IVR menu rule or IVR option* so it's declared in the IVR system and can be retrieved using the call session id.  This would allow you to set a specific value for an IVR option (e.g. a string value) that is independent of the number the custom has used to select it.  

Now we've declared the dependency and decoupled the IVR menu details from it's logical meaning so our code that interprets the result is safer.  In some instances we want the customer to key in  number (like their Customer Id or a PIN number) so that might be a different IVR rule.  This eventually evolves into fully dynamic IVR where the next route chosen depends on a RC customer API callback.

**Comment by embbnux** [comment]
Useful link for IVR: https://medium.com/ringcentral-developers/create-a-telephony-survey-using-the-ringcentral-ivr-scripting-api-525f4ef3c616

Now the IVR api (play, collect) is still in internal beta.  Still need to wait it.
