### ISSUE TITLE
RCAdapter.popupWindow sometimes does not work

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#569]
We are using the `RCAdapter.popupWindow` method to popup the embeddable.  The `RCAdapter.popupWindow` method sometimes does not work to popup the widget.  We are seeing it fail to popup the widget about 50% of the time.

Our setup: When our app loads, we load the Ringcentral Embeddable via RC Adapter method.  We wait until `window.RCAdapter.popupWindow` is a function, then call it.  We notice that the method sometimes fails to popup the window.

We are using Embeddable version 1.7.3.

When the popup fails, we observe this message in the browser console logs:

Error: Time out
    at adapter.js?clientId=DRrv9UrYTVqqiy5QtOkiRA&appServer=https://platform.devtest.ringcentral.com&enableFromNumberSetting=1&disableActiveCallControl=false&multipleTabsSupport=1&disableConferenceCall=false&enablePopup=1:9036

**Comment by embbnux** [comment]
Hi @ElridgeDMello the issue is caused when widget iframe hasn't been loaded, and you call popupWindow.
To avoid time out issue, you need to call `popupWindow` function only after you first receive login status event https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/widget-event.md#login-status-event

**Comment by embbnux** [comment]
Closed by inactive. Feel free to reopen it.
